% Auto-generated by cameraCalibrator app on 22-Mar-2016
%-------------------------------------------------------


% Define images to process
imageFileNames = {'D:\Lagring\Plugg\Examensarbete\Data\CameraCalibration\20160322_143025.jpg',...
    'D:\Lagring\Plugg\Examensarbete\Data\CameraCalibration\20160322_143032.jpg',...
    'D:\Lagring\Plugg\Examensarbete\Data\CameraCalibration\20160322_143045.jpg',...
    'D:\Lagring\Plugg\Examensarbete\Data\CameraCalibration\20160322_143050.jpg',...
    'D:\Lagring\Plugg\Examensarbete\Data\CameraCalibration\20160322_143055.jpg',...
    'D:\Lagring\Plugg\Examensarbete\Data\CameraCalibration\20160322_143103.jpg',...
    'D:\Lagring\Plugg\Examensarbete\Data\CameraCalibration\20160322_143107.jpg',...
    'D:\Lagring\Plugg\Examensarbete\Data\CameraCalibration\20160322_143109.jpg',...
    'D:\Lagring\Plugg\Examensarbete\Data\CameraCalibration\20160322_143111.jpg',...
    'D:\Lagring\Plugg\Examensarbete\Data\CameraCalibration\20160322_143113.jpg',...
    'D:\Lagring\Plugg\Examensarbete\Data\CameraCalibration\20160322_143121.jpg',...
    };

% Detect checkerboards in images
[imagePoints, boardSize, imagesUsed] = detectCheckerboardPoints(imageFileNames);
imageFileNames = imageFileNames(imagesUsed);

% Generate world coordinates of the corners of the squares
squareSize = 35;  % in units of 'mm'
worldPoints = generateCheckerboardPoints(boardSize, squareSize);

% Calibrate the camera
[cameraParams, imagesUsed, estimationErrors] = estimateCameraParameters(imagePoints, worldPoints, ...
    'EstimateSkew', false, 'EstimateTangentialDistortion', false, ...
    'NumRadialDistortionCoefficients', 2, 'WorldUnits', 'mm', ...
    'InitialIntrinsicMatrix', [], 'InitialRadialDistortion', []);

% View reprojection errors
h1=figure; showReprojectionErrors(cameraParams, 'CameraCentric');

% Visualize pattern locations
h2=figure; showExtrinsics(cameraParams, 'CameraCentric');

% Display parameter estimation errors
displayErrors(estimationErrors, cameraParams);

% For example, you can use the calibration data to remove effects of lens distortion.
originalImage = imread(imageFileNames{1});
undistortedImage = undistortImage(originalImage, cameraParams);

% See additional examples of how to use the calibration data.  At the prompt type:
% showdemo('MeasuringPlanarObjectsExample')
% showdemo('StructureFromMotionExample')
